[package]
name = "hreq"
version = "1.0.0"
authors = ["Martin Algesten <martin@lookback.io>"]
edition = "2018"

[features]
default = [
    "tokio",
    "gzip",
    "tls"
]
async-std = [
    "async-std-lib",
]
tokio = [
    "tokio-lib",
]
gzip = [
    "async-compression",
    "flate2"
]
tls = [
    "rustls",
    "webpki",
    "webpki-roots",
]

[dependencies]
bytes = "*"
cookie = "*"
futures-io = { version = "0.3" }
futures-util = { version = "0.3", features=["io"] }
h2 = "*"
http = "*"
httparse = "*"
log = "*"
once_cell = "*"
qstring = "*"
async-trait = "*"
encoding_rs = "*"
# We always need tokio asyncwrite/asyncread traits because h2 uses them.
tokio-traits = { path = "./tokio-traits" }

## async-std
async-std-lib = { package = "async-std", version = "*", optional = true }

## tokio
tokio-lib = { package = "tokio", version = "0.2", default-features = false, features = ["rt-core", "tcp", "dns", "time", "fs"], optional = true }

## gzip
async-compression = { version = "*", default-features = false, features = ["gzip", "futures-bufread"], optional = true }
flate2 = { version = "*", default-features = false, features = [], optional = true }

## tls
rustls = { version = "0.16.0", default-features = false, features = [], optional = true }
webpki = { version = "*", optional = true }
webpki-roots = { version = "*", optional = true }

[dev-dependencies]
tide = "0.6"
async-std-lib = { package = "async-std", version = "*", features = ["unstable"] }
paste = "0.1"
rand = "0.7"

[package.metadata.docs.rs]
all-features = true
