name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --features async-std
    - name: Run tests async-std
      run: cargo test --features async-std
    - name: Run tests tokio
      run: cargo test
